site_name: Documentation
site_url: https://netreplica.com/docs/
edit_uri: ""
docs_dir: docs.md
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: light blue
  logo: ../assets/brand/netreplica-site-header.svg
  favicon: ../assets/brand/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
# Page tree
nav:
  - Home: '../index.html'
  - nrx: nrx/README.md
#  - templates: templates/README.md
  - graphite: graphite/README.md
